import "@/styles/globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Neonote",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" max-w-4xl m-auto">
        <Header />
        {children}
      </body>
    </html>
  );
}
